version: "3.9"

services:

  #Base de datos
  db:
    image: mysql:8.0
    container_name: fct_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gef
      MYSQL_USER: purpor
      MYSQL_PASSWORD: purpor
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./fct_database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fct_net

  #Backend
  backend:
    build:
      context: ./Backend
    container_name: fct_laravel
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - fct_net

  #Frontend
  frontend:
    build:
      context: ./Frontend
    container_name: fct_vue
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - fct_net

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fct_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - fct_net

#Volumenes
volumes:
  db_data:

#Redes
networks:
  fct_net:
    driver: bridge

# Servicio     URL
# Laravel API  http://localhost:8000 http://localhost:8000
# Vue          http://localhost:5173 http://localhost:5173
# phpMyAdmin   http://localhost:8080 http://localhost:8080
# MySQL        localhost:3306

#Para que funcione hacer llo siguiente:
#En el .env poner la configuracion nueva y DB_HOST=-> nombre del servicio, no localhost.
#Entrar a la carpeta Gestor-de-estancias-formativas
#docker-compose down -v
#docker-compose build --no-cache
#docker-compose up -d
#docker exec -it fct_laravel bash
#php artisan key:generate
#php artisan migrate:fresh
#php artisan optimize:clea
